port: 8082
todo_file: path/to/todo.txt

parse_config:
  category_delim: '------'

  date_formats:
  - '%d.%m.%y'
  - '%d.%m.%Y'

  time_format: '%H:%M'

  left_date_bracket: (

  right_date_bracket: )

  left_state_bracket: '['

  right_state_bracket: ']'

  priority_mark: '!'

  tab_size: 4
