name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 26.x
          cache: "npm"

      - name: Fetch dependencies
        run: make dependencies

      - name: Build core
        run: make core

      - name: Build VSCode extension
        run: make vscode-extension BUILD_NUMBER=${GITHUB_RUN_NUMBER}-${GITHUB_SHA:0:7}

      - name: Print version
        id: print_version
        run: make print-version BUILD_NUMBER=${GITHUB_RUN_NUMBER}-${GITHUB_SHA:0:7}

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: commonplace-${{ steps.print_version.outputs.version }}.vsix
